app_user:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
fos_user_security_check:
    path:     /login_check
    defaults: { _controller: AppBundle:Security:check }
fos_user_security_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:check }
