app_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: AppBundle:Default:index }
app_user_view:
    path:     /profile/view/{id}
    defaults: { _controller: AppBundle:Profile:viewUser }